[package]
name = "node-rpc"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
jsonrpc-core = "15.1.0"
node-primitives = { version = "2.0.0", path = "../primitives" }
node-runtime = { version = "2.0.0", path = "../runtime" }
pallet-contracts-rpc = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "master"}
pallet-mmr-rpc = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "master"}
pallet-transaction-payment-rpc = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "master"}
sc-client-api = { version = "3.0.0", path = "../../../client/api" }
sc-consensus-babe = { version = "0.9.0", path = "../../../client/consensus/babe" }
sc-consensus-babe-rpc = { version = "0.9.0", path = "../../../client/consensus/babe/rpc" }
sc-consensus-epochs = { version = "0.9.0", path = "../../../client/consensus/epochs" }
sc-chain-spec = { version = "3.0.0", path = "../../../client/chain-spec" }
sc-finality-grandpa = { version = "0.9.0", path = "../../../client/finality-grandpa" }
sc-finality-grandpa-rpc = { version = "0.9.0", path = "../../../client/finality-grandpa/rpc" }
sc-keystore = { version = "3.0.0", path = "../../../client/keystore" }
sc-rpc-api = { version = "0.9.0", path = "../../../client/rpc-api" }
sc-rpc = { version = "3.0.0", path = "../../../client/rpc" }
sc-sync-state-rpc = { version = "0.9.0", path = "../../../client/sync-state-rpc" }
sp-api = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "master"}
sp-block-builder = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "master"}
sp-blockchain = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "master"}
sp-keystore = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "master"}
sp-consensus = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "master"}
sp-consensus-babe = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "master"}
sp-runtime = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "master"}
sp-transaction-pool = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "master"}
substrate-frame-rpc-system = { version = "3.0.0", path = "../../../utils/frame/rpc/system" }
