[package]
name = "substrate-frame-cli"
version = "3.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "cli interface for FRAME"
documentation = "https://docs.rs/substrate-frame-cli"
readme = "README.md"

[dependencies]
sp-core = { version = "3.0.0", git = "https://github.com/paritytech/substrate", rev="22193e0" }
sc-cli = { version = "0.9.0", path = "../../../client/cli" }
sp-runtime = { version = "3.0.0", git = "https://github.com/paritytech/substrate", rev="22193e0" }
structopt = "0.3.8"
frame-system = { version = "3.0.0", git = "https://github.com/paritytech/substrate", rev="22193e0" }

[dev-dependencies]

[features]
default = []
